name: Flutter CI/CD Pipeline

on:
  push:
    branches: [git_hub_action_test,develop]
  pull_request:
    branches: [git_hub_action_test,develop]

jobs:
  build:
    runs-on: macos-latest

    env:
      ANDROID: ${{ secrets.ANDROID_HOME }}
      ANDROID_SDK: ${{ secrets.ANDROID_HOME }}
      ARCHIVE_DIR: untracked-files-archive

    steps:
      # 1. CHECKOUT ──────────────────────────────
      # Checkout repository code
      - name: 1.1 Checkout code
        uses: actions/checkout@v4

      # 2. FLUTTER SDK SETUP ─────────────────────
      # Set up the Flutter toolchain (add fail-fast)
      - name: 2.1 Set up Flutter SDK
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.32.0'

      # 2.2 Tool Sanity Check
      # Confirm Flutter and Dart are installed properly (fail early)
      - name: Sanity check Flutter & Dart
        run: |
          set -e
          flutter --version
          dart --version

      # 3. ENVIRONMENT & DEPENDENCIES ────────────

      # (A) Cache Dart & Flutter pub packages
      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      # (B) Cache CocoaPods
      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ios/Podfile.lock
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}

      # Create .env file for API endpoints (add fail-fast)
      - name: 3.1 Create .env file
        run: |
          set -e
          echo "DEV_API_BASE_URL=${{ secrets.DEV_API_BASE_URL }}"  > .env
          echo "STAGE_API_BASE_URL=${{ secrets.STAGE_API_BASE_URL }}" >> .env
          echo "PROD_API_BASE_URL=${{ secrets.PROD_API_BASE_URL }}"  >> .env

      # 4. ANDROID + COMMON BUILD ────────────────
      # Clean previous builds (fail-fast)
      - name: 4.1 Flutter clean
        run: set -e; flutter clean

      # Install dependencies and run code generation (fail-fast)
      - name: 4.2 Pub get & code generation
        run: |
          set -e
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      # Run all unit and widget tests (including goldens)
      - name: 4.3 Run unit and widget tests
        run: set -e; flutter test
        env:
          CI: true
      # Archive failed golden images if 'flutter test' fails
      - name: Archive failed golden images if any
        if: failure()
        run: |
          set -e
          rm -rf failed-goldens-archive
          mkdir -p failed-goldens-archive
          failure_files=$(find test -type d -name "failures" -exec find {} -type f \;)
          if [ -n "$failure_files" ]; then
            printf "%s\n" "$failure_files" | while IFS= read -r file; do
              cp --parents "$file" failed-goldens-archive/
            done
            tar -czf failed-golden-images.tar.gz -C failed-goldens-archive .
          fi

      # Upload the archive as an artifact on failure
      - name: Upload failed golden images
        if: failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: failed-golden-images
          path: failed-golden-images.tar.gz

      # Install Flutterfire CLI for Firebase integration (fail-fast)

      - name: 4.4 Install Flutterfire CLI
        run: set -e; dart pub global activate flutterfire_cli

      # 5. ANDROID SIGNING AND BUILD ─────────────
      # Decode Android keystore (fail-fast)
      - name: 5.1 Decode Android Keystore
        run: |
          set -e
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      # Create key.properties for signing (fail-fast)
      - name: 5.2 Create key.properties
        run: |
          set -e
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      # Build Android APKs for dev and stage flavors (fail-fast)
      - name: 5.3 Build Android APKs (dev and stage)
        run: |
          set -e
          flutter build apk --flavor dev   --dart-define=APP_FLAVOR=DEV --release
          flutter build apk --flavor stage --dart-define=APP_FLAVOR=STAGE --release
          flutter build apk --flavor prod --dart-define=APP_FLAVOR=PROD --release

      # 6. iOS SETUP ─────────────────────────────
      # Set up Xcode environment
      - name: 6.1 Setup Xcode environment
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      # Install CocoaPods and dependencies (fail-fast)
      - name: 6.2 Fresh CocoaPods install
        run: |
          set -e
          sudo gem install cocoapods
          cd ios
          pod install --repo-update
          cd ..

      # 7. iOS CERTIFICATES, PROFILES, AND BUILD ─────────────────────
      # --- DEV FLAVOR ---
      # Decode dev certificates and ExportOptions (fail-fast)
      - name: 7.1.1 Decode iOS Certificates & Profiles (dev)
        run: |
          set -e
          echo "${{ secrets.P12_BASE64 }}" | base64 --decode > certificate.p12
          echo "${{ secrets.P12_PASSWORD }}" > p12_password.txt
          echo "${{ secrets.PROFILE_DEV_BASE64 }}" | base64 --decode > profile_dev.mobileprovision
          echo "${{ secrets.EXPORTOPTIONS_DEV_BASE64 }}" | base64 --decode > ExportOptionsDev.plist

      # Set up keychain and import certificate (fail-fast)
      - name: 7.1.2 Set up iOS keychain & import certificate
        run: |
          set -e
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security import certificate.p12 -k build.keychain -P $(cat p12_password.txt) -A
          security set-key-partition-list -S apple-tool:,apple: -k "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain

      # Install provisioning profile for dev flavor (fail-fast)
      - name: 7.1.3 Install provisioning profile (dev)
        run: |
          set -e
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile_dev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Build IPA for dev flavor (fail-fast)
      - name: 7.1.4 Build IPA (dev)
        run: set -e; flutter build ipa --flavor dev --export-options-plist=ExportOptionsDev.plist --release

      # Rename IPA for dev flavor (fail-fast)
      - name: Rename IPA (dev)
        run: set -e; mv "build/ios/ipa/Flutter Skeleton Dev.ipa" build/ios/ipa/app-dev.ipa

      # --- STAGE FLAVOR ---
      # Install provisioning profile for stage flavor (fail-fast)
      - name: 7.2.1 Install provisioning profile (stage)
        run: |
          set -e
          echo "${{ secrets.PROFILE_STAGE_BASE64 }}" | base64 --decode > profile_stage.mobileprovision
          cp profile_stage.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "${{ secrets.EXPORTOPTIONS_STAGE_BASE64 }}" | base64 --decode > ExportOptionsStage.plist

      # Build IPA for stage flavor (fail-fast)
      - name: 7.2.2 Build IPA (stage)
        run: set -e; flutter build ipa --flavor stage --export-options-plist=ExportOptionsStage.plist --release

      # Rename IPA for stage flavor (fail-fast)
      - name: Rename IPA (stage)
        run: set -e; mv "build/ios/ipa/Flutter Skeleton Stage.ipa" build/ios/ipa/app-stage.ipa

      # --- PROD FLAVOR ---
      # Install provisioning profile for prod flavor (fail-fast)
      - name: 7.3.1 Install provisioning profile (prod)
        run: |
          set -e
          echo "${{ secrets.PROFILE_PROD_BASE64 }}" | base64 --decode > profile_prod.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile_prod.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "${{ secrets.EXPORTOPTIONS_PROD_BASE64 }}" | base64 --decode > ExportOptionsProd.plist

      # Build IPA for prod flavor (fail-fast)
      - name: 7.3.2 Build IPA (prod)
        run: set -e; flutter build ipa --flavor prod --export-options-plist=ExportOptionsProd.plist --release

      # Rename IPA for prod flavor (fail-fast)
      - name: Rename IPA (prod)
        run: set -e; mv "build/ios/ipa/Flutter Skeleton.ipa" build/ios/ipa/app-prod.ipa

      # 8. UPLOAD ARTIFACTS ──────────────────────
      # Upload Android dev APK
      - name: 8.1 Upload APK (dev)
        if: success()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: apk-dev-release
          path: build/app/outputs/flutter-apk/app-dev-release.apk

      # Upload Android stage APK
      - name: 8.2 Upload APK (stage)
        if: success()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: apk-stage-release
          path: build/app/outputs/flutter-apk/app-stage-release.apk

      # Upload iOS dev IPA
      - name: 8.3 Upload IPA (dev)
        if: success()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ipa-dev-release
          path: build/ios/ipa/app-dev.ipa

      # Upload iOS stage IPA
      - name: 8.4 Upload IPA (stage)
        if: success()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ipa-stage-release
          path: build/ios/ipa/app-stage.ipa

      # Upload iOS prod IPA
      - name: 8.5 Upload IPA (prod)
        if: success()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ipa-prod-release
          path: build/ios/ipa/app-prod.ipa

      # Upload build logs on failure for debug
      - name: Upload build logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-logs
          path: |
            build/**/logs/*.log
            build/**/logs/*.txt
            build/**/failures/**/*

      # 9. Cleanup secrets and keychain ─────────────────────
      # Explicitly remove sensitive/temporary files including .env (fail-fast)
      - name: 9. Cleanup secrets and keychain
        if: always()
        run: |
          set -e
          rm -f android/app/keystore.jks android/key.properties
          rm -f certificate.p12 p12_password.txt profile_*.mobileprovision ExportOptions*.plist .env
          rm -f build/ios/ipa/app-*.ipa
          security delete-keychain build.keychain || true
